/*
 * DIO_config.c
 *
 *  Created on: Sep 10, 2022
 *      Author: Mostafa Sayed
 */
#include "DIO_config.h"
#include "../../Units.h"
#include "DIO_Types.h"


DIO_Configuration Pins_list[] =
{
		// KEYPAD
		{PORT_C,PIN_0,OUTPUT,PULLUP_OFF},
		{PORT_C,PIN_1,OUTPUT,PULLUP_OFF},
		{PORT_C,PIN_2,OUTPUT,PULLUP_OFF},
		{PORT_C,PIN_3,OUTPUT,PULLUP_OFF},
		{PORT_C,PIN_4,INPUT,PULLUP_ON},
		{PORT_C,PIN_5,INPUT,PULLUP_ON},
		{PORT_C,PIN_6,INPUT,PULLUP_ON},
		{PORT_C,PIN_7,INPUT,PULLUP_ON},

		// LCD
		{PORT_A,PIN_0,OUTPUT,PULLUP_OFF},
		{PORT_A,PIN_1,OUTPUT,PULLUP_OFF},
		{PORT_A,PIN_2,OUTPUT,PULLUP_OFF},
		{PORT_A,PIN_3,OUTPUT,PULLUP_OFF},
		{PORT_A,PIN_4,OUTPUT,PULLUP_OFF},
		{PORT_A,PIN_5,OUTPUT,PULLUP_OFF},
		{PORT_A,PIN_6,OUTPUT,PULLUP_OFF},
		{PORT_A,PIN_7,OUTPUT,PULLUP_OFF},

		// Interrupt
		{PORT_D,PIN_0,OUTPUT,PULLUP_OFF},
		{PORT_D,PIN_1,OUTPUT,PULLUP_OFF}
};
